package com.opengamma.strata.product.cms;

import java.io.Serializable;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.product.swap.SwapLeg;

@BeanDefinition
public final class Cms
    implements CmsProduct, ImmutableBean, Serializable {

  @PropertyDefinition(validate = "notNull")
  private final CmsLeg cmsLeg;

  @PropertyDefinition(validate = "notNull")
  private final SwapLeg paymentLeg;

  // TODO check single currency, same start and end, fixed(?), pay and rec

  @Override
  public ExpandedCms expand() {
    return ExpandedCms.builder().cmsLeg(cmsLeg.expand()).paymentLeg(paymentLeg.expand()).build();
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code Cms}.
   * @return the meta-bean, not null
   */
  public static Cms.Meta meta() {
    return Cms.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(Cms.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static Cms.Builder builder() {
    return new Cms.Builder();
  }

  private Cms(
      CmsLeg cmsLeg,
      SwapLeg paymentLeg) {
    JodaBeanUtils.notNull(cmsLeg, "cmsLeg");
    JodaBeanUtils.notNull(paymentLeg, "paymentLeg");
    this.cmsLeg = cmsLeg;
    this.paymentLeg = paymentLeg;
  }

  @Override
  public Cms.Meta metaBean() {
    return Cms.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the cmsLeg.
   * @return the value of the property, not null
   */
  public CmsLeg getCmsLeg() {
    return cmsLeg;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the paymentLeg.
   * @return the value of the property, not null
   */
  public SwapLeg getPaymentLeg() {
    return paymentLeg;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      Cms other = (Cms) obj;
      return JodaBeanUtils.equal(cmsLeg, other.cmsLeg) &&
          JodaBeanUtils.equal(paymentLeg, other.paymentLeg);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(cmsLeg);
    hash = hash * 31 + JodaBeanUtils.hashCode(paymentLeg);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("Cms{");
    buf.append("cmsLeg").append('=').append(cmsLeg).append(',').append(' ');
    buf.append("paymentLeg").append('=').append(JodaBeanUtils.toString(paymentLeg));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code Cms}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code cmsLeg} property.
     */
    private final MetaProperty<CmsLeg> cmsLeg = DirectMetaProperty.ofImmutable(
        this, "cmsLeg", Cms.class, CmsLeg.class);
    /**
     * The meta-property for the {@code paymentLeg} property.
     */
    private final MetaProperty<SwapLeg> paymentLeg = DirectMetaProperty.ofImmutable(
        this, "paymentLeg", Cms.class, SwapLeg.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "cmsLeg",
        "paymentLeg");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1356515323:  // cmsLeg
          return cmsLeg;
        case 1612870184:  // paymentLeg
          return paymentLeg;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public Cms.Builder builder() {
      return new Cms.Builder();
    }

    @Override
    public Class<? extends Cms> beanType() {
      return Cms.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code cmsLeg} property.
     * @return the meta-property, not null
     */
    public MetaProperty<CmsLeg> cmsLeg() {
      return cmsLeg;
    }

    /**
     * The meta-property for the {@code paymentLeg} property.
     * @return the meta-property, not null
     */
    public MetaProperty<SwapLeg> paymentLeg() {
      return paymentLeg;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -1356515323:  // cmsLeg
          return ((Cms) bean).getCmsLeg();
        case 1612870184:  // paymentLeg
          return ((Cms) bean).getPaymentLeg();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code Cms}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<Cms> {

    private CmsLeg cmsLeg;
    private SwapLeg paymentLeg;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(Cms beanToCopy) {
      this.cmsLeg = beanToCopy.getCmsLeg();
      this.paymentLeg = beanToCopy.getPaymentLeg();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -1356515323:  // cmsLeg
          return cmsLeg;
        case 1612870184:  // paymentLeg
          return paymentLeg;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -1356515323:  // cmsLeg
          this.cmsLeg = (CmsLeg) newValue;
          break;
        case 1612870184:  // paymentLeg
          this.paymentLeg = (SwapLeg) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public Cms build() {
      return new Cms(
          cmsLeg,
          paymentLeg);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the cmsLeg.
     * @param cmsLeg  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder cmsLeg(CmsLeg cmsLeg) {
      JodaBeanUtils.notNull(cmsLeg, "cmsLeg");
      this.cmsLeg = cmsLeg;
      return this;
    }

    /**
     * Sets the paymentLeg.
     * @param paymentLeg  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder paymentLeg(SwapLeg paymentLeg) {
      JodaBeanUtils.notNull(paymentLeg, "paymentLeg");
      this.paymentLeg = paymentLeg;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(96);
      buf.append("Cms.Builder{");
      buf.append("cmsLeg").append('=').append(JodaBeanUtils.toString(cmsLeg)).append(',').append(' ');
      buf.append("paymentLeg").append('=').append(JodaBeanUtils.toString(paymentLeg));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
